### ISSUE TITLE
Implementation for the restart() method

### ISSUE THREAD

**Issue by andela-mallan** [meharbhutta/react-native-circular-timer#2]
Awesome library here @meharbhutta.
However, I have searched for an implementation of the restart() method to no avail.
Could you kindly provide one? Most probably in the documentation so that someone else could find it.

**Comment by meharbhutta** [comment]
Thanks @andela-mallan.
Added the implementation of the restart() method in v1.0.1.

**Comment by majidzeno** [comment]
just add ref to your timer then call 
`state={key:0}`
`<CircularTimer
 key={this.state.key}
 ref={refs => (this._timerRef = refs)} 
.... />
`
then call it from a restart button 
 `<TouchableOpacity
  onPress={() => {
   this._timerRef.restart()
   this.setState(prevState => ({
   key: prevState.key + 1,
  }))
`
Notice: I gave my component a key with a number and increase it every time to force the timer to unmount to clear the timer, or the timer will start counting down with 2 seconds if you pressed it again before the time ends and so on.
